# Generated by Django 3.2.3 on 2021-05-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalejecutivo',
            name='apellido',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalejecutivo',
            name='nombre',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalsucursal',
            name='apellido',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalsucursal',
            name='nombre',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
