# Generated by Django 3.2.3 on 2021-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_productos_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='farmacia',
        ),
        migrations.AddField(
            model_name='producto',
            name='farmacia',
            field=models.ManyToManyField(blank=True, null=True, to='app.Farmacia'),
        ),
    ]
