# Generated by Django 3.2.3 on 2021-05-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210515_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='farmacia',
        ),
        migrations.AddField(
            model_name='producto',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.farmacia'),
        ),
    ]
