# Generated by Django 3.2.3 on 2021-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210515_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Contado'), ('Débito', 'Tarjeta de débito'), ('Crédito', 'Tarjeta de crédito')], max_length=10, null=True),
        ),
    ]
