# Generated by Django 3.2.3 on 2021-05-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210519_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal',
            new_name='PersonalSucursal',
        ),
    ]
