# Generated by Django 3.2.3 on 2021-05-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_personal_personalsucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEjecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('legajo', models.CharField(blank=True, max_length=10, null=True)),
                ('cargo', models.CharField(blank=True, choices=[('Dir', 'Director'), ('CE', 'Comite Ejecutivo'), ('DT', 'Directores Técnicos'), ('Aux', 'Auxiliares')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
